name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build_android:
    name: Build Android
    type: build
    params:
      platform: android
      profile: production
  build_ios:
    name: Build iOS
    type: build
    params:
      platform: ios
      profile: production
  submit_android:
    name: Submit Android
    type: submit
    needs:
      - build_android
    params:
      platform: android
      profile: production
  submit_ios:
    name: Submit iOS
    type: submit
    needs:
      - build_ios
    params:
      platform: ios
      profile: production
