name: Development Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    steps:
      - checkout
      - run: npm ci
      - run: eas build --profile development --platform all --non-interactive
