name: Preview Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    steps:
      - checkout
      - run: npm ci
      - run: eas build --profile preview --platform all --non-interactive
